source "https://rubygems.org"
gem "jekyll", "~> 4.3.0"
gem "webrick" # Required for Ruby >= 3.0
gem 'faraday-retry'
require 'faraday'
require 'faraday/retry'

conn = Faraday.new do |faraday|
  faraday.request :retry, max: 3, interval: 0.5, backoff_factor: 2  # Customize as needed
  faraday.adapter Faraday.default_adapter
end
